// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { defaultContext, QueryClient, QueryClientProvider } from '/Users/daipei/daipeihust/myapp/node_modules/.pnpm/@tanstack+react-query@4.29.5_react-dom@17.0.2_react@17.0.2/node_modules/@tanstack/react-query';
import { ReactQueryDevtools } from '/Users/daipei/daipeihust/myapp/node_modules/.pnpm/@tanstack+react-query-devtools@4.29.5_@tanstack+react-query@4.29.5_react-dom@17.0.2_react@17.0.2/node_modules/@tanstack/react-query-devtools';
const reactQueryConfig = {};
const client = new QueryClient(reactQueryConfig.queryClient || {});
export function rootContainer(container) {
  return (
    <QueryClientProvider client={client} context={defaultContext}>
      {container}
      <ReactQueryDevtools context={defaultContext} initialIsOpen={false} {...(reactQueryConfig.devtool || {})} />
    </QueryClientProvider>
  );
}
