// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export type {
  // from @tanstack/query-core
  Query, QueryState, Mutation,
  // from @tanstack/react-query
  QueriesResults,
  QueriesOptions,
  QueryErrorResetBoundaryProps,
  QueryClientProviderProps,
  ContextOptions as QueryContextOptions,
  UseQueryOptions,
  UseBaseQueryOptions,
  UseQueryResult,
  UseBaseQueryResult,
  UseInfiniteQueryOptions,
  UseMutationResult,
  UseMutateFunction,
  UseMutateAsyncFunction,
  UseBaseMutationResult,
} from '/Users/daipei/daipeihust/myapp/node_modules/.pnpm/@tanstack+react-query@4.29.5_react-dom@17.0.2_react@17.0.2/node_modules/@tanstack/react-query';
